# Generated by CMake, DO NOT EDIT

empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/data/github/ccbasic/src/script/luacmake/CMakeLists.txt))

/Volumes/data/github/ccbasic/buildios/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/bin/cmake -H/Volumes/data/github/ccbasic -B/Volumes/data/github/ccbasic/buildios
