# Generated by CMake, DO NOT EDIT

empty:= 
space:= $(empty) $(empty)
spaceplus:= $(empty)\ $(empty)

TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/data/github/ccbasic/buildios/CMakeFiles/CheckTypeSize/OFF64_T.c))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/data/github/ccbasic/src/script/zlibcmake/../../../3rd/zlib/zconf.h.cmakein))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/data/github/ccbasic/src/script/zlibcmake/../../../3rd/zlib/zlib.pc.cmakein))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /Volumes/data/github/ccbasic/src/script/zlibcmake/CMakeLists.txt))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckCSourceCompiles.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckFunctionExists.c))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckFunctionExists.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckIncludeFile.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckIncludeFile.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckIncludeFileCXX.cmake))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckTypeSize.c.in))
TARGETS += $(subst $(space),$(spaceplus),$(wildcard /usr/local/share/cmake-3.9/Modules/CheckTypeSize.cmake))

/Volumes/data/github/ccbasic/buildios/CMakeFiles/cmake.check_cache: $(TARGETS)
	/usr/local/bin/cmake -H/Volumes/data/github/ccbasic -B/Volumes/data/github/ccbasic/buildios
